name: SmartSpawner
version: '${version}'
main: github.nighter.smartspawner.SmartSpawner
api-version: '1.20'
authors: [ https://github.com/ptthanh02/Smart-Spawner/graphs/contributors ]
folia-supported: true
softdepend:
  # Shop Plugins
  - EconomyShopGUI
  - EconomyShopGUI-Premium
  - ShopGUIPlus
  - zShop
  - ExcellentShop

  # Utility/Economy Plugins
  - CoinEngine
  - Vault

  # Protection/Region Plugins
  - WorldGuard
  - GriefPrevention
  - Lands
  - Towny
  - SimpleClaimSystem
  - RedProtect
  - MinePlots

  # World Management Plugins
  - Multiverse-Core
  - MultiWorld
  - Worlds
  - SuperiorSkyblock2

  # RPG/Skill Plugins
  - AuraSkills

  #Drops Plugins
  - MythicMobs

commands:
  smartspawner:
    description: Main command for SmartSpawner plugin
    aliases: [ ss, spawner ]
  smartSellwand:
    description: Command to sell items in spawner storage GUI
    usage: /smartSellwand
    permission: smartspawner.sellwand

permissions:
  smartspawner.reload:
    description: Permission to reload SmartSpawner plugin
    default: op
  smartspawner.give:
    description: Allow giving spawners to yourself or other players
    default: op
  smartspawner.list:
    description: Allow viewing list of spawners and teleporting to them
    default: op
  smartspawner.hologram:
    description: Allow toggling hologram for spawners
    default: op
  smartspawner.changetype:
    description: Allow changing spawner type with spawn egg
    default: op
  smartspawner.stack:
    description: Allow stacking spawners
    default: true
  smartspawner.break:
    description: Allow breaking spawners
    default: true
  smartspawner.sellall:
    description: Allow selling items in spawner storage GUI
    default: true
  smartspawner.limits.bypass:
    description: Bypass spawner limits per chunk
    default: false

